### ISSUE TITLE
'skip' option does not work with 'null' value

### ISSUE THREAD

**Issue by Grawl** [jonathantneal/postcss-short-overflow#1]
`"postcss-short-overflow": "1.0.0"`

I am trying to use this plugin with Sass, and I [just found](https://github.com/jonathantneal/postcss-short/issues/6#issuecomment-275567152) a tip to use `null` instead of `*` to avoid of Sass syntax errors.

Input:

```css
html {
    overflow: null auto;
}
```

Output:

```css
html {
	overflow-x: null;
	overflow-y: auto;
	-webkit-overflow-scrolling: touch;
}
```

`postcss.config.js`:

```js
module.exports = ctx => {
	return {
		plugins: {
			'postcss-assets': { loadPaths: [ 'node_modules' ] },
			'postcss-inline-svg': {},
			'postcss-axis': {},
			'postcss-short': {
				skip: 'null',
			},
			'postcss-position-alt': {},
			'postcss-single-charset': {},
			'postcss-image-set-polyfill': {},
			'postcss-momentum-scrolling': [ 'auto', 'scroll' ],
			'postcss-easings': {},
			'autoprefixer': {},
		},
	}
}
```

If I change `skip: 'null'` to `skip: '*'`, output is expected:

```css
html {
	overflow-y: auto;
	-webkit-overflow-scrolling: touch;
}
```

It works fine with other `postcss-short-*` plugins.
